// Package workspace provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package workspace

import (
	corev1alpha1 "github.com/meshery/schemas/models/v1alpha1/core"
)

// Workspace defines model for workspace.
type Workspace struct {
	ID        corev1alpha1.GeneralId `db:"id" json:"id" yaml:"id"`
	CreatedAt corev1alpha1.Time      `json:"created_at,omitempty" yaml:"created_at,omitempty"`

	// DeletedAt SQL null Timestamp to handle null values of time.
	DeletedAt   corev1alpha1.NullTime `json:"deleted_at,omitempty" yaml:"deleted_at,omitempty"`
	Description corev1alpha1.Text     `json:"description,omitempty" yaml:"description,omitempty"`
	Name        corev1alpha1.Text     `json:"name,omitempty" yaml:"name,omitempty"`

	// OrganizationId A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	OrganizationID *corev1alpha1.Uuid `db:"organization_id" json:"organization_id" yaml:"organization_id"`
	Owner          corev1alpha1.Text  `json:"owner,omitempty" yaml:"owner,omitempty"`
	UpdatedAt      corev1alpha1.Time  `json:"updated_at,omitempty" yaml:"updated_at,omitempty"`
}

// WorkspacePage defines model for workspacePage.
type WorkspacePage struct {
	Page       corev1alpha1.Number `json:"page,omitempty" yaml:"page,omitempty"`
	PageSize   corev1alpha1.Number `json:"page_size,omitempty" yaml:"page_size,omitempty"`
	TotalCount corev1alpha1.Number `json:"total_count,omitempty" yaml:"total_count,omitempty"`
	Workspaces []Workspace         `json:"workspaces,omitempty" yaml:"workspaces,omitempty"`
}

// WorkspacePayload defines model for workspacePayload.
type WorkspacePayload struct {
	Description corev1alpha1.Text `json:"description,omitempty" yaml:"description,omitempty"`
	Name        corev1alpha1.Text `json:"name" yaml:"name"`

	// OrganizationId A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	OrganizationID corev1alpha1.Uuid `json:"organization_id" yaml:"organization_id"`
}

// WorkspaceUpdatePayload defines model for workspaceUpdatePayload.
type WorkspaceUpdatePayload struct {
	Description corev1alpha1.Text `json:"description,omitempty" yaml:"description,omitempty"`
	Name        corev1alpha1.Text `json:"name,omitempty" yaml:"name,omitempty"`

	// OrganizationId A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	OrganizationID corev1alpha1.Uuid `json:"organization_id" yaml:"organization_id"`
}

// WorkspacesDesignsMapping defines model for workspacesDesignsMapping.
type WorkspacesDesignsMapping struct {
	ID        corev1alpha1.GeneralId `db:"id" json:"id" yaml:"id"`
	CreatedAt corev1alpha1.Time      `json:"created_at,omitempty" yaml:"created_at,omitempty"`

	// DeletedAt SQL null Timestamp to handle null values of time.
	DeletedAt   corev1alpha1.NullTime    `json:"deleted_at,omitempty" yaml:"deleted_at,omitempty"`
	DesignId    corev1alpha1.Uuid        `db:"design_id" json:"design_id" yaml:"design_id"`
	UpdatedAt   corev1alpha1.Time        `json:"updated_at,omitempty" yaml:"updated_at,omitempty"`
	WorkspaceId corev1alpha1.WorkspaceId `db:"workspace_id" json:"workspace_id" yaml:"workspace_id"`
}

// WorkspacesEnvironmentsMapping defines model for workspacesEnvironmentsMapping.
type WorkspacesEnvironmentsMapping struct {
	ID        corev1alpha1.GeneralId `db:"id" json:"id" yaml:"id"`
	CreatedAt corev1alpha1.Time      `json:"created_at,omitempty" yaml:"created_at,omitempty"`

	// DeletedAt SQL null Timestamp to handle null values of time.
	DeletedAt     corev1alpha1.NullTime      `json:"deleted_at,omitempty" yaml:"deleted_at,omitempty"`
	EnvironmentId corev1alpha1.EnvironmentId `db:"environment_id" json:"environment_id" yaml:"environment_id"`
	UpdatedAt     corev1alpha1.Time          `json:"updated_at,omitempty" yaml:"updated_at,omitempty"`
	WorkspaceId   corev1alpha1.WorkspaceId   `db:"workspace_id" json:"workspace_id" yaml:"workspace_id"`
}

// WorkspacesTeamsMapping defines model for workspacesTeamsMapping.
type WorkspacesTeamsMapping struct {
	ID        corev1alpha1.GeneralId `db:"id" json:"id" yaml:"id"`
	CreatedAt corev1alpha1.Time      `json:"created_at,omitempty" yaml:"created_at,omitempty"`

	// DeletedAt SQL null Timestamp to handle null values of time.
	DeletedAt   corev1alpha1.NullTime    `json:"deleted_at,omitempty" yaml:"deleted_at,omitempty"`
	TeamId      corev1alpha1.TeamId      `db:"team_id" json:"team_id" yaml:"team_id"`
	UpdatedAt   corev1alpha1.Time        `json:"updated_at,omitempty" yaml:"updated_at,omitempty"`
	WorkspaceId corev1alpha1.WorkspaceId `db:"workspace_id" json:"workspace_id" yaml:"workspace_id"`
}

// WorkspacesViewsMapping defines model for workspacesViewsMapping.
type WorkspacesViewsMapping struct {
	ID        corev1alpha1.GeneralId `db:"id" json:"id" yaml:"id"`
	CreatedAt corev1alpha1.Time      `json:"created_at,omitempty" yaml:"created_at,omitempty"`

	// DeletedAt SQL null Timestamp to handle null values of time.
	DeletedAt   corev1alpha1.NullTime    `json:"deleted_at,omitempty" yaml:"deleted_at,omitempty"`
	UpdatedAt   corev1alpha1.Time        `json:"updated_at,omitempty" yaml:"updated_at,omitempty"`
	ViewId      corev1alpha1.ViewId      `db:"view_id" json:"view_id" yaml:"view_id"`
	WorkspaceId corev1alpha1.WorkspaceId `db:"workspace_id" json:"workspace_id" yaml:"workspace_id"`
}
